# Generated by Django 3.0.4 on 2020-12-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone', models.BigIntegerField()),
                ('Username', models.CharField(max_length=100)),
                ('Userid', models.AutoField(primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
