# Generated by Django 3.0.4 on 2020-12-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
    ]
